on:
  pull_request:
jobs:
  build:
    name: >-
      Ruby ${{ matrix.ruby }} (${{ matrix.gemfile }})
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby:
          - '3.1'
          - '3.2'
        gemfile:
          - gemfiles/rails_6.gemfile
          - gemfiles/rails_7.gemfile
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: latest
      - name: Run tests
        timeout-minutes: 10
        run: bundle exec rake spec