name: release
on:
  push:
    branches:
      - master
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: ruby
          package-name: sparkpost_rails
          bump-minor-pre-major: true
          version-file: "lib/sparkpost_rails/version.rb"